services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    user: 1000:1000
    volumes:
      - ../../data/autobrr/config:/config
      - ${USB}/torrents:/data/torrents
    ports:
      - 7474:7474
networks:
  default:
    name: media_server_default
    external: true
