services:
  jdownloader:
    container_name: jdownloader
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - SECURE_CONNECTION=${VNC_SECURE_CONNECTION}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - ENABLE_CJK_FONT=1
    image: jlesage/jdownloader-2
    ports:
      - 1500:5800
    restart: unless-stopped
    volumes:
      - ../../data/jdownloader-2/config:/config:rw
      - ${JDOWNLOADER_FOLDER}:/output:rw
      - ${JDOWNLOADER_FOLDER}:${JDOWNLOADER_FOLDER}:rw
    networks:
      - default
      - traefik-proxy
networks:
  traefik-proxy:
    external: true
