services:
    open-webui:
        ports:
            - 3050:8080
        volumes:
            - ../../data/ollama:/root/.ollama
            - ../../data/open-webui:/app/backend/data
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:ollama
