services:
   autoheal:
    container_name: autoheal
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
      AUTOHEAL_ONLY_MONITOR_RUNNING: false
      AUTOHEAL_INTERVAL: 60
    image: willfarrell/autoheal:latest
    network_mode: none
    restart: no
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
