services:
  czkawka:
    #container_name: czkawka_deploy1
    restart: always
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - SECURE_CONNECTION=${VNC_SECURE_CONNECTION}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - ENABLE_CJK_FONT=1
    image: jlesage/czkawka
    ports:
      - 1601-1603:5800
    volumes:
      - ../../data/czkawka/config/results_similar_videos_pretty.json:/config/results_similar_videos_pretty.json:rw
      - ../../data/czkawka/cache:/config/xdg/cache:rw
      - /mnt:/mnt:rw
    deploy:
      mode: replicated
      replicas: 3
networks: {}
