services:
  autoscan:
    container_name: autoscan
    depends_on:
      plex:
        condition: service_healthy
      jellyfin:
        condition: service_healthy
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 5s
      test:
        - CMD-SHELL
        - cat /data/media/media_no_local.anchor
      timeout: 10s
    image: cloudb0x/autoscan
    ports:
      - 3030:3030
    restart: always
    volumes:
      - ../../data/media_server/autoscan/config:/config
      - ${MEDIA}:/data/media:ro
  flaresolverr:
    container_name: flaresolverr
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    image: flaresolverr/flaresolverr:latest
    ports:
      - 8191:8191
    restart: unless-stopped
  jellyfin:
    container_name: jellyfin
    depends_on:
      rclone_media:
        condition: service_healthy
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${SERVER_DOMAIN}
      - JELLYFIN_FFmpeg__probesize=62000000
      - JELLYFIN_FFmpeg__analyzeduration=62000000
    group_add:
      - "110"
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 2m00s
      test:
        - CMD-SHELL
        - cat /data/media/media_no_local.anchor && curl --connect-timeout 15
          --silent --show-error --fail "http://localhost:8096/health"
      timeout: 15s
    hostname: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 8096:8096
      - 7359:7359
      - 1900:1900
    restart: unless-stopped
    volumes:
      - ../../data/media_server/jellyfin/config:/config
      - ${MEDIA}:/data/media:ro
  overseerr:
    container_name: overseerr
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=debug
      - PORT=5055
    image: sctx/overseerr:latest
    ports:
      - 5055:5055
    restart: unless-stopped
    volumes:
      - ../../data/media_server/overseerr/config:/app/config
  plex:
    container_name: plex
    depends_on:
      rclone_media:
        condition: service_healthy
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - VERSION=docker
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 2m00s
      test:
        - CMD-SHELL
        - cat /data/media/media_no_local.anchor && curl --connect-timeout 15
          --silent --show-error --fail "http://localhost:32400/identity"
      timeout: 10s
    hostname: plex
    image: linuxserver/plex:latest
    ports:
      - 32400:32400
      - 32401:32401
      - 33400:33400
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: always
    tmpfs:
      - /config/Library/Application Support/Plex Media
        Server/Cache/PhotoTranscoder
      - /config/transcode
    volumes:
      - ../../data/media_server/plex/config:/config
      - ${MEDIA}:/data/media:rw
  prowlarr:
    container_name: prowlarr
    depends_on:
      - flaresolverr
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    restart: unless-stopped
    volumes:
      - ../../data/media_server/prowlarr/config:/config
  radarr:
    container_name: radarr
    depends_on:
      prowlarr:
        condition: service_started
      rclone_media:
        condition: service_healthy
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 5s
      test:
        - CMD-SHELL
        - cat /data/media/media_no_local.anchor
      timeout: 10s
    image: lscr.io/linuxserver/radarr:latest
    logging:
      driver: json-file
    ports:
      - 7878:7878
    restart: unless-stopped
    volumes:
      - ../../data/media_server/radarr/config:/config
      - ${MEDIA}:/data/media:rw
      - ${TORRENTS_FOLDER}:/data/torrents:rw
  rclone_media:
    group_add:
      - "999"
    cap_add:
      - SYS_ADMIN
    command: "mount media: /data --allow-non-empty --allow-other --dir-cache-time
      500h --poll-interval 150s --vfs-disk-space-total-size 256T --tpslimit 8
      --tpslimit-burst 3 --log-level DEBUG"
    container_name: rclone_media
    devices:
      - /dev/fuse:/dev/fuse:rwm
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - UMASK=022
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 5s
      test:
        - CMD-SHELL
        - cat /data/media_no_local.anchor
      timeout: 10s
    image: rclone/rclone:latest
    restart: always
    security_opt:
      - apparmor:unconfined
    volumes:
      - ../../rclone:/config/rclone
      - ../../data/media_server/media_local:/media_local_subs
      - ${DATA}/media_local_mkv:/media_local_mkv
      - ${MEDIA}:/data:rshared
  rdt-client:
    container_name: rdt-client
    image: rogerfar/rdtclient:latest
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 6500:6500
    profiles:
      - disabled
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}/rdt-client:/data/downloads
      - ../../data/media_server/rdt-client:/data/db
  sonarr:
    container_name: sonarr
    depends_on:
      prowlarr:
        condition: service_started
      rclone_media:
        condition: service_healthy
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 5s
      test:
        - CMD-SHELL
        - cat /data/media/media_no_local.anchor
      timeout: 10s
    image: lscr.io/linuxserver/sonarr:latest
    logging:
      driver: json-file
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - ../../data/media_server/sonarr/config:/config
      - ${MEDIA}:/data/media:rw
      - ${TORRENTS_FOLDER}:/data/torrents:rw
  tautulli:
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
    image: lscr.io/linuxserver/tautulli:latest
    ports:
      - 8181:8181
    restart: always
    volumes:
      - ../../data/media_server/tautulli/config:/config
  tdarr:
    container_name: tdarr
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=internalDockerNode
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - 8265:8265
      - 8266:8266
    profiles:
      - disabled
    volumes:
      - ../../data/media_server/tdarr/server:/app/server
      - ../../data/media_server/tdarr/config:/app/configs
      - ../../data/media_server/tdarr/logs:/app/logs
      - ../../data/media_server/tdarr_temp:/temp
      - ${MEDIA}:/data/media
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    user: 1000:1000
    volumes:
      - ../../data/media_server/autobrr/config:/config
      - ${USB}/torrents:/data/torrents
    ports:
      - 7474:7474
networks:
  default:
    name: media_server
  traefik-proxy:
    external: true
